# Generated by Django 4.0.3 on 2022-04-09 01:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admins', '0040_alter_login_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page_acces',
            name='page',
        ),
        migrations.AddField(
            model_name='page_acces',
            name='advanced_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page_acces',
            name='avanced_record',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page_acces',
            name='company_report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page_acces',
            name='documents',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page_acces',
            name='new_record',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page_acces',
            name='upload',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page_acces',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='login',
            name='last_login',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 4, 9, 7, 29, 36, 489819)),
        ),
    ]
