# Generated by Django 4.0.3 on 2022-03-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancefcompany',
            name='NetAmount',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newfcompany',
            name='depostieAmount',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newfcompany',
            name='netAmount',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newfcompany',
            name='paymenetAmount',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
