# Generated by Django 3.2.6 on 2022-03-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_advancefcompany_netamount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newfcompany',
            name='netAmount',
            field=models.CharField(blank=True, default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='uplaodingdocument',
            name='documentFile',
            field=models.FileField(upload_to='../static'),
        ),
    ]
