# Generated by Django 3.2.6 on 2022-03-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20220324_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uplaodingdocument',
            name='documentFile',
            field=models.FileField(upload_to='static/'),
        ),
    ]
