# Generated by Django 3.2.6 on 2022-03-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_rename_documentfile_uplaodingdocument_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newfcompany',
            name='depostieAmount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='newfcompany',
            name='netAmount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='newfcompany',
            name='paymenetAmount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
