# Generated by Django 3.2.6 on 2022-03-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_auto_20220327_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancefcompany',
            name='receiDepPay',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
