# Generated by Django 4.0.3 on 2022-04-09 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0046_alter_page_acces_admin'),
        ('documents', '0009_uplaodingdocument_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newfcompany',
            name='FCompany',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.f_company'),
        ),
    ]
