# Generated by Django 4.0.3 on 2022-04-10 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0046_alter_page_acces_admin'),
        ('documents', '0011_alter_uplaodingdocument_documenttype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancefcompany',
            name='FCompany',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins.f_company'),
        ),
    ]
