# Generated by Django 4.0.3 on 2022-04-10 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_newfcompany'),
    ]

    operations = [
        migrations.DeleteModel(
            name='newFCompany',
        ),
    ]
