# Generated by Django 4.0.3 on 2022-04-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_alter_advancefcompany_reclink_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancefcompany',
            name='NetAmount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advancefcompany',
            name='depositeAmount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advancefcompany',
            name='details',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advancefcompany',
            name='paymentAmount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
